// app/src/components/Chat.svelte
<script lang="ts">
  import { onDestroy, tick } from "svelte";
  import { messages, connected, agentState } from "../lib/stores";
  import { send } from "../lib/ws";
  import { linkify } from "../lib/linkify";
  import { createAutoScroller } from "../lib/scroll";
  import "../styles/panel.css";
  import type { VestaEvent } from "../lib/types";

  let { name, onBack }: { name: string; onBack: () => void } = $props();

  type Line = { id: number; text: string; kind: string; time: string };
  const MAX_MESSAGES = 5000;
  let lines = $state<Line[]>([]);
  let nextId = 0;
  let input = $state("");
  let showTools = $state(false);
  let outputEl: HTMLDivElement;
  let inputEl: HTMLTextAreaElement;

  let wasConnected = $state(false);
  let suppressAnim = $state(false);
  const scroller = createAutoScroller(() => outputEl);

  function fmtTime(iso?: string) {
    if (!iso) return "";
    const d = new Date(iso);
    return `${String(d.getHours()).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`;
  }

  function eventToLine(ev: VestaEvent): Line | null {
    const time = fmtTime(ev.ts);
    if (ev.type === "user") return { id: nextId++, text: `> ${ev.text}`, kind: "user", time };
    if (ev.type === "assistant") return { id: nextId++, text: ev.text, kind: "assistant", time };
    if (ev.type === "tool_start") return { id: nextId++, text: `[${ev.tool}] ${ev.input}`, kind: "tool", time };
    if (ev.type === "tool_end") return { id: nextId++, text: `[${ev.tool}] done`, kind: "tool", time };
    if (ev.type === "notification") return { id: nextId++, text: `[${ev.source}] ${ev.summary}`, kind: "notification", time };
    if (ev.type === "error") return { id: nextId++, text: `error: ${ev.text}`, kind: "error", time };
    return null;
  }

  let lastSyncedLen = 0;
  let lastArray: VestaEvent[] = [];

  let pendingUserTexts = new Map<string, number>();

  const unsubMessages = messages.subscribe((evts) => {
    if (evts !== lastArray) {
      lines = [];
      nextId = 0;
      lastSyncedLen = 0;
      pendingUserTexts.clear();
      suppressAnim = true;
      requestAnimationFrame(() => { suppressAnim = false; });
    }
    for (let i = lastSyncedLen; i < evts.length; i++) {
      const ev = evts[i];
      if (ev.type === "user") {
        const count = pendingUserTexts.get(ev.text) ?? 0;
        if (count > 0) {
          if (count === 1) pendingUserTexts.delete(ev.text);
          else pendingUserTexts.set(ev.text, count - 1);
          continue;
        }
      }
      const line = eventToLine(ev);
      if (line) lines.push(line);
    }
    if (lines.length > MAX_MESSAGES) lines.splice(0, lines.length - MAX_MESSAGES);
    lastSyncedLen = evts.length;
    lastArray = evts;
    lines = lines;
    scroller.scroll();
  });

  $effect(() => {
    if ($connected) {
      wasConnected = true;
      tick().then(() => inputEl?.focus());
    }
  });

  onDestroy(() => {
    unsubMessages();
  });

  function handleSend() {
    const msg = input.trim();
    if (!msg) return;
    if (send(msg)) {
      pendingUserTexts.set(msg, (pendingUserTexts.get(msg) ?? 0) + 1);
      lines.push({ id: nextId++, text: `> ${msg}`, kind: "user", time: fmtTime(new Date().toISOString()) });
      lines = lines;
      scroller.scroll();
      input = "";
      resizeInput();
    }
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  }

  function handleGlobalKeydown(e: KeyboardEvent) {
    if (e.key === "Escape" && (!input.trim() || document.activeElement !== inputEl)) {
      onBack();
    }
  }

  function resizeInput() {
    if (!inputEl) return;
    inputEl.style.height = "auto";
    inputEl.style.height = Math.min(inputEl.scrollHeight, 120) + "px";
  }

  let thinking = $derived($agentState === "thinking" || $agentState === "tool_use");

  let stableConnected = $state(false);
  let disconnectTimer: ReturnType<typeof setTimeout> | null = null;
  $effect(() => {
    if ($connected) {
      if (disconnectTimer) { clearTimeout(disconnectTimer); disconnectTimer = null; }
      stableConnected = true;
    } else {
      disconnectTimer = setTimeout(() => { stableConnected = false; }, 2000);
    }
  });
  onDestroy(() => { if (disconnectTimer) clearTimeout(disconnectTimer); });
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div class="panel" onkeydown={handleGlobalKeydown}>
  <div class="topbar">
    <button class="back-btn" onclick={onBack} aria-label="back" data-tip="back">
      <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
        <polyline points="15 18 9 12 15 6"/>
      </svg>
    </button>
    <div class="topbar-info">
      <span class="title">{name}</span>
      <span class="dot" class:connected={stableConnected} class:thinking title={!stableConnected ? "disconnected" : thinking ? ($agentState === "tool_use" ? "using a tool" : "thinking") : "connected"}></span>
    </div>
    <button class="tool-toggle" class:active={showTools} onclick={() => { showTools = !showTools; tick().then(() => { if (outputEl) outputEl.scrollTop = outputEl.scrollHeight; }); }} aria-label="show tool activity" data-tip={showTools ? "hide tools" : "show tools"}>
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
        <path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/>
      </svg>
    </button>
  </div>

  <div class="output" class:no-anim={suppressAnim} bind:this={outputEl} onscroll={scroller.check}>
    {#each lines as line (line.id)}
      {#if (line.kind !== "tool" && line.kind !== "notification") || showTools}
        <div class="line {line.kind}"><span class="ts">{line.time}</span>{@html linkify(line.text)}</div>
      {/if}
    {/each}
    {#if thinking && lines.length > 0}
      <div class="line thinking-indicator"><span></span><span></span><span></span></div>
    {/if}
    {#if lines.length === 0}
      <div class="empty-state">
        <div class="empty-dots"><span></span><span></span><span></span></div>
        <span class="empty-label">{$connected ? `${name} is listening. say something.` : "connecting..."}</span>
      </div>
    {/if}
  </div>

  <div class="reconnect-bar" class:visible={!$connected && wasConnected}>reconnecting...</div>

  <form class="input-bar" onsubmit={(e) => { e.preventDefault(); handleSend(); }}>
    <span class="prompt-char">&gt;</span>
    <textarea
      rows="1"
      placeholder={$connected ? "send a message..." : "connecting..."}
      bind:value={input}
      bind:this={inputEl}
      disabled={!$connected}
      oninput={resizeInput}
      onkeydown={handleKeydown}
    ></textarea>
  </form>
</div>

<style>
  .dot {
    width: 6px;
    height: 6px;
    border-radius: 50%;
    background: rgba(255, 255, 255, 0.15);
    transition: all 0.4s var(--spring);
  }

  .dot.connected {
    background: #66bb6a;
    box-shadow: 0 0 6px rgba(102, 187, 106, 0.4);
  }

  .dot.connected.thinking {
    background: #ffa726;
    box-shadow: 0 0 6px rgba(255, 167, 38, 0.4);
  }

  .tool-toggle {
    margin-left: auto;
    background: transparent;
    border: none;
    color: rgba(255, 255, 255, 0.25);
    cursor: pointer;
    min-width: 44px;
    min-height: 44px;
    padding: 0;
    border-radius: 8px;
    corner-shape: squircle;
    transition: all 0.2s var(--spring);
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .tool-toggle:hover {
    color: rgba(255, 255, 255, 0.5);
    background: rgba(255, 255, 255, 0.05);
  }

  .tool-toggle:active {
    transform: scale(0.95);
  }

  .tool-toggle.active {
    color: rgba(255, 255, 255, 0.7);
    background: rgba(255, 255, 255, 0.08);
  }

  .ts {
    color: rgba(255, 255, 255, 0.2);
    margin-right: 8px;
    font-size: 11px;
    user-select: none;
  }

  .line.user { color: rgba(255, 255, 255, 0.9); }
  .line.assistant { color: rgba(140, 200, 130, 0.9); }
  .line.tool { color: rgba(255, 255, 255, 0.4); font-size: 11px; }
  .line.notification { color: rgba(255, 200, 100, 0.7); font-size: 11px; }
  .line.error { color: rgba(224, 112, 112, 0.9); }

  .thinking-indicator {
    display: flex;
    gap: 4px;
    padding: 4px 0;
  }

  .thinking-indicator span {
    width: 4px;
    height: 4px;
    border-radius: 50%;
    background: rgba(140, 200, 130, 0.5);
    animation: dot-pulse 1.4s ease-in-out infinite;
  }

  .thinking-indicator span:nth-child(2) { animation-delay: 0.2s; }
  .thinking-indicator span:nth-child(3) { animation-delay: 0.4s; }

  .reconnect-bar {
    padding: 0;
    max-height: 0;
    overflow: hidden;
    font-size: 11px;
    color: rgba(255, 200, 100, 0.8);
    background: rgba(255, 200, 100, 0.06);
    border-top: 1px solid transparent;
    text-align: center;
    user-select: none;
    opacity: 0;
    transition: max-height 0.2s var(--spring), opacity 0.2s var(--spring), padding 0.2s var(--spring), border-color 0.2s var(--spring);
  }

  .reconnect-bar.visible {
    padding: 6px 20px;
    max-height: 40px;
    opacity: 1;
    border-top-color: rgba(255, 200, 100, 0.1);
  }

  .input-bar {
    display: flex;
    align-items: flex-start;
    gap: 8px;
    padding: 12px 20px;
    border-top: 1px solid rgba(255, 255, 255, 0.05);
    flex-shrink: 0;
    background: rgba(255, 255, 255, 0.02);
  }

  .prompt-char {
    color: rgba(255, 255, 255, 0.35);
    font-family: "SF Mono", "Fira Code", "JetBrains Mono", "Consolas", monospace;
    font-size: 13px;
    line-height: 1.4;
    font-weight: 500;
    flex-shrink: 0;
    user-select: none;
  }

  .input-bar textarea {
    flex: 1;
    background: transparent;
    border: none;
    outline: none;
    resize: none;
    padding: 0;
    margin: 0;
    overflow-y: auto;
    font-family: "SF Mono", "Fira Code", "JetBrains Mono", "Consolas", monospace;
    font-size: 13px;
    line-height: 1.4;
    color: rgba(255, 255, 255, 0.75);
    caret-color: rgba(255, 255, 255, 0.4);
    max-height: 120px;
  }

  .input-bar textarea::-webkit-scrollbar { width: 4px; }
  .input-bar textarea::-webkit-scrollbar-track { background: transparent; }
  .input-bar textarea::-webkit-scrollbar-thumb { background: rgba(255, 255, 255, 0.1); border-radius: 2px; }

  .input-bar textarea::placeholder { color: rgba(255, 255, 255, 0.35); }
  .input-bar textarea:disabled { opacity: 0.25; cursor: not-allowed; }

  .input-bar:has(textarea:focus-visible) {
    border-top-color: rgba(255, 255, 255, 0.12);
  }
</style>

// app/src/components/Chat/index.tsx
import {
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
} from "react";
import { Maximize2, PanelRightClose, SendHorizontal } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { AnimatePresence, motion } from "motion/react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardFooter,
} from "@/components/ui/card";
import { useAgentWs } from "@/hooks/use-agent-ws";
import { useAutoScroll } from "@/hooks/use-auto-scroll";
import { useSelectedAgent } from "@/providers/SelectedAgentProvider";
import { linkify } from "@/lib/linkify";
import type { VestaEvent } from "@/lib/types";
import { cn } from "@/lib/utils";

interface ChatProps {
  onCollapse?: () => void;
  fullscreen?: boolean;
}

export function Chat({ onCollapse, fullscreen }: ChatProps = {}) {
  const { name, setAgentState } = useSelectedAgent();
  const navigate = useNavigate();
  const { messages, agentState, connected, send } = useAgentWs(name, true);

  useEffect(() => {
    setAgentState(agentState);
  }, [agentState, setAgentState]);

  const [input, setInput] = useState("");
  const [wasConnected, setWasConnected] = useState(false);
  const [showReconnect, setShowReconnect] = useState(false);

  const scrollRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const { check, scroll } = useAutoScroll();

  const reconnectTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    if (connected) {
      setWasConnected(true);
      setShowReconnect(false);
      if (reconnectTimerRef.current) {
        clearTimeout(reconnectTimerRef.current);
        reconnectTimerRef.current = null;
      }
    } else if (wasConnected) {
      reconnectTimerRef.current = setTimeout(() => {
        setShowReconnect(true);
      }, 2000);
    }
    return () => {
      if (reconnectTimerRef.current) clearTimeout(reconnectTimerRef.current);
    };
  }, [connected, wasConnected]);

  const filteredMessages = messages.filter(
    (m) =>
      m.type !== "tool_start" &&
      m.type !== "tool_end" &&
      m.type !== "notification",
  );

  useLayoutEffect(() => {
    scroll(scrollRef.current);
  }, [filteredMessages, scroll]);

  const handleScroll = () => {
    check(scrollRef.current);
  };

  const handleSend = () => {
    const text = input.trim();
    if (!text) return;
    if (send(text)) {
      setInput("");
      const ta = textareaRef.current;
      if (ta) ta.style.height = "auto";
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleInput = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setInput(e.target.value);
    const ta = e.target;
    ta.style.height = "auto";
    ta.style.height = `${Math.min(ta.scrollHeight, 120)}px`;
  };

  const isThinking =
    agentState === "thinking" || agentState === "tool_use";

  return (
    <Card className={cn(
      "flex flex-col h-full gap-0 py-0 overflow-hidden relative",
      fullscreen && "border-0 rounded-none shadow-none bg-background",
    )}>

      {!fullscreen && (
        <div className="absolute top-3 right-3 z-10 flex items-center gap-0.5">
          {onCollapse && (
            <Button
              size="icon-sm"
              variant="ghost"
              className="text-muted-foreground"
              onClick={onCollapse}
            >
              <PanelRightClose />
            </Button>
          )}
          <Button
            size="icon-sm"
            variant="ghost"
            className="text-muted-foreground"
            onClick={() => navigate(`/agent/${name}/chat`)}
          >
            <Maximize2 />
          </Button>
        </div>
      )}

      <AnimatePresence>
        {showReconnect && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="text-center py-2 bg-amber-500/10 text-amber-600 dark:text-amber-400 text-xs overflow-hidden shrink-0"
          >
            reconnecting...
          </motion.div>
        )}
      </AnimatePresence>

      <CardContent className="flex-1 overflow-y-auto p-0 px-4 py-3 min-h-0">
        <div
          ref={scrollRef}
          onScroll={handleScroll}
          className="h-full overflow-y-auto font-mono text-sm leading-relaxed"
        >
          <div className="min-h-full flex flex-col justify-end">
            <div>
              {filteredMessages.length === 0 ? (
                <div className="flex flex-col items-center gap-2 py-2">
                  <ThinkingDots />
                  <span className="text-xs text-muted-foreground">
                    {connected
                      ? `${name} is listening`
                      : "connecting..."}
                  </span>
                </div>
              ) : (
                <>
                  {filteredMessages.map((msg, i) => (
                    <MessageLine key={i} event={msg} />
                  ))}
                  <AnimatePresence>
                    {isThinking && filteredMessages.length > 0 && (
                      <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        transition={{ duration: 0.15 }}
                      >
                        <ThinkingDots />
                      </motion.div>
                    )}
                  </AnimatePresence>
                </>
              )}
            </div>
          </div>
        </div>
      </CardContent>

      <CardFooter className="border-t shrink-0 p-3 px-4 !pt-3">
        <div className="flex items-end gap-2.5 w-full">
          <textarea
            ref={textareaRef}
            value={input}
            onChange={handleInput}
            onKeyDown={handleKeyDown}
            placeholder={connected ? "send a message..." : "connecting..."}
            disabled={!connected}
            rows={1}
            className="m-0 flex-1 min-h-9 max-h-[120px] bg-transparent py-2.5 text-sm font-mono leading-5 resize-none outline-none placeholder:text-muted-foreground/50 disabled:opacity-50"
          />
          <Button
            size="icon-sm"
            variant="ghost"
            className="shrink-0"
            disabled={!connected || !input.trim()}
            onClick={handleSend}
          >
            <SendHorizontal className="text-muted-foreground" />
          </Button>
        </div>
      </CardFooter>
    </Card>
  );
}

function MessageLine({ event }: { event: VestaEvent }) {
  if (event.type === "history") return null;

  const ts = event.ts
    ? new Date(event.ts).toLocaleTimeString("en-US", {
      hour: "2-digit",
      minute: "2-digit",
      hour12: false,
    })
    : "";

  let colorClass = "text-primary";
  let content = "";

  switch (event.type) {
    case "user":
      colorClass = "text-foreground font-medium";
      content = `> ${event.text}`;
      break;
    case "assistant":
      colorClass = "text-primary/90";
      content = event.text;
      break;
    case "tool_start":
      colorClass = "text-muted-foreground text-xs";
      content = `[${event.tool}] ${event.input}`;
      break;
    case "tool_end":
      colorClass = "text-muted-foreground text-xs";
      content = `[${event.tool}] done`;
      break;
    case "notification":
      colorClass = "text-amber-600 dark:text-amber-400 text-xs";
      content = `[${event.source}] ${event.summary}`;
      break;
    case "error":
      colorClass = "text-destructive";
      content = `error: ${event.text}`;
      break;
    case "status":
      return null;
    default:
      return null;
  }

  return (
    <div className={cn("flex gap-2 py-[1px]", colorClass)}>
      {ts && (
        <span className="text-xs text-muted-foreground/40 shrink-0 leading-[1.9] select-none">
          {ts}
        </span>
      )}
      <span
        className="break-words min-w-0"
        dangerouslySetInnerHTML={{ __html: linkify(content) }}
      />
    </div>
  );
}

function ThinkingDots() {
  return (
    <div className="flex items-center gap-1 py-1">
      <div className="size-[5px] rounded-full bg-primary/60 opacity-60" />
      <div className="size-[5px] rounded-full bg-primary/60 opacity-40" />
      <div className="size-[5px] rounded-full bg-primary/60 opacity-20" />
    </div>
  );
}
